services:
  backend:
    container_name: honeypot_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  honeypot_listener:
    container_name: honeypot_listener
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # locally listen on these ports and forward to honeypot_listener container port 8001
      - "8080:8001"
      - "8081:8001"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: uvicorn app.main_honeypot:app --host 0.0.0.0 --port 8001

  honeypot_ssh:
    container_name: honeypot_ssh
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: python -u -m app.ssh.run
    environment:
      - SSH_HOST_KEY=/app/host_key_dir/host_key

  honeypot_ftp:
    container_name: honeypot_ftp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2121:21" # FTP control port
      - "50000-50010:50000-50010" # FTP passive data ports
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: python -u -m app.ftp.run

  db:
    image: postgres:15
    container_name: honeypot_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: honeypot_redis
    restart: always
    command: ["redis-server"]

  # for database management GUI
  pgadmin:
    image: dpage/pgadmin4
    container_name: honeypot_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "127.0.0.1:5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
    name: honeypot_postgres_data
